inherit_mode:
  merge:
    - Exclude # For GitHub Actions. See: https://github.com/rubocop/rubocop/issues/9832#issuecomment-1624219788

require:
 - rubocop-rails
 - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
