require:
 - rubocop-rails
 - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
