# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: mybase_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:alpine
        ports:
          - "6379:6379"
        options: --entrypoint redis-server --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/mybase_test"
      DOMAIN: 127.0.0.1:3000
      MAGIC_LINK_SECRET_KEY: 8ab2bb212ed03da4f489ae3b14726df97117b224b9003da191396c446661c1efe209bcee17cdeacb01d9f7abfb9307b9eb122d71d38522bd65abbe9ba8df8940
      REDIS_URL: redis://localhost:6379/0
      SECRET_KEY_BASE: b49d2311335f06f8b9be0c8f3bfe0c98250363f6bb9f133c421075c5a7428dbdef40700437fef80be98165d50240df0c3e7cc66d71cfcdd3f6b69729d0f64764
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Node dependencies (mjml for email)
        run: npm install

      - name: Set up Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up database
        run: bin/rails db:setup

      - name: Run tests
        run: bin/rails test

      - name: Run system tests
        run: bin/rails test:system

  lint:
    name: Lint and scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop --parallel

      - name: Scan for security vulnerabilities
        run: bundle exec brakeman -q -w2
